DROP TABLE IF EXISTS Review
GO
CREATE TABLE Review
(
	ReviewID		UNIQUEIDENTIFIER	NOT NULL IDENTITY (1, 1),
	AuthorID		UNIQUEIDENTIFIER	NOT NULL,
	SolutionID		UNIQUEIDENTIFIER	NOT NULL,
	Posted			DATETIMEOFFSET		NOT NULL,

	CONSTRAINT PK_REVIEW				PRIMARY KEY (ReviewID),
	CONSTRAINT FK_REVIEW_AUTHOR_ID		FOREIGN KEY (AuthorID) REFERENCES ResourceUser(UserID),
	CONSTRAINT FK_REVIEW_SOLUTION_ID	FOREIGN KEY (SolutionID) REFERENCES Solution(SolutionID),
	CONSTRAINT CH_REVIEW_POSTED			CHECK (Posted > '2018-05-12 00:00:00')
)